services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker -v

install:
  - docker network create --subnet=172.18.0.0/16 hdpnet1
  - travis_retry docker build --add-host=sandbox:127.0.0.1 -t sandbox .
  - travis_retry docker run -itd -h sandbox --net hdpnet1 --ip 172.18.0.22 sandbox

script:
  - docker ps
  - travis_wait 5 sleep 180
  - docker ps | grep -q sandbox
  - curl -sL -w "%{http_code}\\n" "http://172.18.0.22:8080"
  - travis_retry curl -sL -w "%{http_code}\\n" "http://172.18.0.22:8080" -o /dev/null | grep 200
  - travis_retry curl -sL -w "%{http_code}\\n" "http://172.18.0.22:8088" -o /dev/null | grep 200
